### ISSUE TITLE
barrett hand plugin not loaded in rqt under Ubuntu xenial 16.04 w/ ROS kinetic 

### ISSUE THREAD

**Issue by anaceri** [RobotnikAutomation/barrett_hand#10]
Hi there, 

I facing an issue of loading the barrett hand plugin either using rqt or via the `$rosrun rqt_bhand rqt_bhand` under Ubuntu xenial 16.04 and ROS kinetic. In both, I get the following error:
```
RosPluginProvider.load(rqt_bhand/BHandGUI) exception raised in __builtin__.__import__(rqt_bhand.rqt_bhand, [BHandGUI]):
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 80, in load
    module = __builtin__.__import__(attributes['module_name'], fromlist=[attributes['class_from_class_type']], level=0)
  File "/home/djallil/Gazebo_tutorials/barrett_rviz/src/rqt_bhand/src/rqt_bhand/rqt_bhand.py", line 38, in <module>
    from python_qt_binding.QtCore import Qt, QTimer, Slot, QBasicTimer, SIGNAL
ImportError: cannot import name SIGNAL

PluginManager._load_plugin() could not load plugin "rqt_bhand/BHandGUI":
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler.py", line 99, in load
    self._load()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/plugin_handler_direct.py", line 54, in _load
    self._plugin = self._plugin_provider.load(self._instance_id.plugin_id, self._context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui_py/ros_py_plugin_provider.py", line 60, in load
    return super(RosPyPluginProvider, self).load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/qt_gui/composite_plugin_provider.py", line 71, in load
    instance = plugin_provider.load(plugin_id, plugin_context)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_gui/ros_plugin_provider.py", line 86, in load
    raise e
ImportError: cannot import name SIGNAL
```
Any idea?

Thanks in advance!

**Comment by RomanRobotnik** [comment]
Hi,

Unfortunately, the rqt_bhand plugin was not migrated to Kinetic and the new
qt version, sorry.


2018-06-20 11:27 GMT+02:00 anaceri <notifications@github.com>:

**Comment by anaceri** [comment]
Thanks for prompt reply. Any plan to do so? PS. in ROS.org it says this version is also supported in Kinetic.
